schema_version: 1

context:
  name: tangogql
  version: "2.2.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tangogql-${{ version }}.tar.gz
  sha256: 8ee4818e8201e403719f03133473e78bcfc667b3155e82b412045cd834e8c762

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - pytango
    - ariadne
    - uvicorn
    - python-dateutil
    - aiocache
    - aiodataloader
    - pyjwt
    - pydantic-settings
    - websockets

tests:
  - python:
      imports:
        - tangogql
      python_version:
        - ${{ python_min }}.*
        - 3.*
      pip_check: true

about:
  summary: TangoGQL implementation using Ariadne
  description: This is a GraphQL schema and implementation for accessing a Tango control system.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  homepage: https://gitlab.com/tango-controls/web/tangogql-ariadne
  repository: https://gitlab.com/tango-controls/web/tangogql-ariadne

extra:
  recipe-maintainers:
    - beenje
